// react-todo/src/App.js
import NewTodo from "./components/NewTodo/NewTodo";
import Todos from "./components/Todos/Todos";
import "./App.css";

function App() {
  return (
    <div className="App">
      <div className="container">
        <div className="container-header">
          <h1>What is your plan for today?</h1>
        </div>
        <div className="container-body">
          <NewTodo />
          <Todos />
        </div>
      </div>
    </div>
  );
}

export default App;

// svelte-todo/src/App.svelte
<script>
	import NewTodo from "./components/NewTodo.svelte";
	import Todos from "./components/Todos.svelte";
</script>

<main>
  <div class="App">
    <div class="container">
      <div class="container-header">
        <h1>What is your plan for today?</h1>
      </div>
      <div class="container-body">
		<NewTodo />
		<Todos />
	  </div>
    </div>
  </div>
</main>

<style>
</style>
