// react-todo/src/components/NewTodo/NewTodo.jsx
import { useState, useContext } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSquarePlus } from "@fortawesome/free-solid-svg-icons";

import { TodosContext } from "../../TodosContext";
import "./NewTodo.css";

export default function NewTodo() {
  const [todo, setTodo] = useState("");
  const { addTodo } = useContext(TodosContext);

  return (
    <div className="newtodo-container">
      <input
        type="text"
        placeholder="What you plan to do?"
        value={todo}
        onChange={(e) => setTodo(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            addTodo(e.target.value);
            setTodo("");
          }
        }}
      />
      <div
        className="add-btn"
        onClick={() => {
          addTodo(todo);
          setTodo("");
        }}
      >
        <FontAwesomeIcon icon={faSquarePlus} />
        <span>Add</span>
      </div>
    </div>
  );
}

// svelte-todo/src/components/NewTodo.svelte
<script>
  import Fa from "svelte-fa";
  import { faSquarePlus } from "@fortawesome/free-solid-svg-icons";
  import { addTodo } from "../stores";

  let todo = "";
</script>

<div class="newtodo-container">
  <input
    type="text"
    placeholder="What you plan do to?"
    bind:value={todo}
    on:keydown={(e) => {
      if (e.key === "Enter") {
        addTodo(e.target.value);
        todo = "";
      }
    }}
  />
  <div
    class="add-btn"
    on:click={() => {
      addTodo(todo);
      todo = "";
    }}
  >
    <Fa icon={faSquarePlus} scale={1.38} />
    <span>Add</span>
  </div>
</div>

<style>
  .newtodo-container {
    display: flex;
    justify-content: space-between;
    width: 80%;
    margin: 0 auto;
    margin-top: 50px;
    color: #1da1f2;
  }

  .newtodo-container input {
    width: 79%;
    border: 1px solid #1da1f2;
    border-radius: 4px;
    padding: 12px 20px;
    font-size: 16px;
    outline: none;
  }

  .add-btn {
    display: flex;
    justify-content: space-evenly;
    align-items: center;
    padding: 10px 21.5px;
    background: rgba(29, 161, 242, 0.17);
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
  }

  .add-btn > span {
    margin-left: 0.75rem;
  }
</style>
